### ISSUE TITLE
Test/improve navigation IA

### ISSUE THREAD

**Issue by maya** [18F/accessibility-playbook#10]
The current main navigation is: Product | Content | UX | Visual design | Front-end

The pages themselves expand to their full title Product management | Content design | UX design | Visual design | Front-end development

Some folks thought that it's too vague as is. That spelling out some of the navigation items could make it clearer. However, they were shortened due to lack of space at the top.

Additional feedback:
>What if the five major categories at the top were reduced to four and more explicitly referred to the person’s role. For example: “Project Managers | Content Authors | Designers | Developers”. Or if that’s too long “Responsibility | Content | Design | Develop”.

#14

**Comment by coreycaitlin** [comment]
Where did the concern about vagueness come from? Can you say more about the worry here? (I just want to make sure I'm solving the right problem as I start exploring options.)

**Comment by coreycaitlin** [comment]
Hi @maya! I'm going to look for a time when we can chat for just a few minutes — I want to make sure I'm solving the right problems here!
